version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:14.3-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: store
    ports:
      - 5432:5432
    networks:
      - api-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']

  api:
    image: username/demo-backend:1.0.0
    container_name: demo-backend-api
    build: ./
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - api-network
    environment:
      - PORT=8000
      - DB_HOST=db
      - DB_PASSWORD=passowrd.
      - DB_NAME=store
      - DB_USER=postgres
      - DB_PORT=5432
      - RESPONSE_LIMIT=10000
      - APP_CORS=*
      - MACIG_KEY=jalksd;fjl;kasdfkl;daslk;faslk;fjakls;dflk;
      - RPC=https://opt-goerli.g.alchemy.com/v2/pM-NCzrzuFgZxHj-ICsFWfEddslwcM1s8_Y
    platform: linux/amd64

volumes:
  my-db:

networks:
  api-network: